### ISSUE TITLE
Problem when running the examples

### ISSUE THREAD

**Issue by TeaBough** [intljusticemission/react-big-calendar#164]
Here is what I get right after doing a `npm install` and `npm run examples 3000`
```
> react-big-calendar@0.10.3 examples /home/tibo/src/react-big-calendar
> npm run clean:examples && webpack-dev-server --inline --hot --config webpack/examples.config.es6.js "3000"


> react-big-calendar@0.10.3 clean:examples /home/tibo/src/react-big-calendar
> rimraf examples/static

/home/tibo/src/react-big-calendar/node_modules/webpack/bin/convert-argv.js:558
                                var i = content.indexOf("=");
                                                ^

TypeError: content.indexOf is not a function
    at /home/tibo/src/react-big-calendar/node_modules/webpack/bin/convert-argv.js:558:21
    at Array.forEach (native)
    at processOptions (/home/tibo/src/react-big-calendar/node_modules/webpack/bin/convert-argv.js:557:11)
    at processConfiguredOptions (/home/tibo/src/react-big-calendar/node_modules/webpack/bin/convert-argv.js:104:4)
    at module.exports (/home/tibo/src/react-big-calendar/node_modules/webpack/bin/convert-argv.js:83:9)
    at Object.<anonymous> (/home/tibo/src/react-big-calendar/node_modules/webpack-dev-server/bin/webpack-dev-server.js:62:48)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

npm ERR! Linux 4.7.1-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "examples" "3000"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! react-big-calendar@0.10.3 examples: `npm run clean:examples && webpack-dev-server --inline --hot --config webpack/examples.config.es6.js "3000"`
npm ERR! Exit status 1

```

**Comment by dkunzman1** [comment]
I'm getting the same thing,  Does anyone have any ideas?

> react-big-calendar@0.10.3 examples /Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar
> npm run clean:examples && webpack-dev-server --inline --hot --config webpack/examples.config.es6.js "3000"


> react-big-calendar@0.10.3 clean:examples /Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar
> rimraf examples/static

/Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar/node_modules/webpack/bin/convert-argv.js:558
				var i = content.indexOf("=");
				                ^

TypeError: content.indexOf is not a function
    at /Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar/node_modules/webpack/bin/convert-argv.js:558:21
    at Array.forEach (native)
    at processOptions (/Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar/node_modules/webpack/bin/convert-argv.js:557:11)
    at processConfiguredOptions (/Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar/node_modules/webpack/bin/convert-argv.js:104:4)
    at module.exports (/Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar/node_modules/webpack/bin/convert-argv.js:83:9)
    at Object.<anonymous> (/Users/douglaskunzman/big-calendar/react-big-calendar2/react-big-calendar/node_modules/webpack-dev-server/bin/webpack-dev-server.js:62:48)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by fxfactorial** [comment]
@TeaBough @dkunzman1 its because you passed 3000, its actually running at 8080. It told you that if you read the starting console logs, 

```
 http://localhost:8080/
webpack result is served from /examples
content is served from /Users/Edgar/Repos/react-big-calendar
```

**Comment by TeaBough** [comment]
yep but in the README you can read : 
```
Clone this repository
Retrieve dependencies: npm install
Start: npm run examples [port] (default port is 3000)
Open localhost:3000/examples/index.html.
```

I guess the read me should be updated, that's all.
