### ISSUE TITLE
Could you do an update to lodash 4.5?

### ISSUE THREAD

**Issue by joewood** [intljusticemission/react-big-calendar#44]
Realize there are some big changes, but it would help to resolve build conflicts.

**Comment by jquense** [comment]
What conflicts are you referring too? We cherry-pick the methods we use so there shouldn't be a problem with having multiple versions.

**Comment by joewood** [comment]
Sorry, you're right. Reinstalling put npm and webpack right again. It's now using a local version.

**Comment by danpantry** [comment]
https://github.com/lodash/lodash/wiki/Changelog#v400

You refer to `lodash/utility/range` - this is now `lodash/range` in lodash 4.5.0.

**Comment by jquense** [comment]
@danpantry thats not how npm and bundlers like webpack/browserify handle dependencies, in the case of two packages that depend on incompatible versions both will be installed. In your case redux-dev-tools will pull in whatever utility functions it needs from lodash 4 and big-calendar will pull in range from v3

**Comment by danpantry** [comment]
It appears I have an older version of npm (somehow - I'm going to elect to blame Windows here) - this was a bug fixed in [npm 3.8.8](https://github.com/npm/npm/commit/86028e9fd8524d5e520ce01ba2ebab5a030103fc).

**Comment by danpantry** [comment]
I *did* write a PR to test this but I seem completely unable to actually build your solution. `babel-preset-jason` is reporting an error...

```
$ babel src --out-dir lib
Error: Plugin 0 specified in "c:\\projects\\@danpantry\\react-big-calendar\\node_modules\\babel-preset-jason\\index.js" provided an invalid property of "default"
    at Plugin.init (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\plugin.js:124:13)
    at Function.normalisePlugin (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:155:12)
    at c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:161:20)
    at OptionManager.mergeOptions (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:254:36)
    at OptionManager.mergePresets (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:308:16)
    at OptionManager.mergeOptions (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:270:12)
    at OptionManager.addConfig (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:206:10)
    at OptionManager.findConfigs (c:\Users\CSUKDNPY\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:347:16)

```

I'm not convinced that installing an entirely different version of the same library is really justified, but ¯\_(ツ)_/¯ I'll just update my npm instead

**Comment by jquense** [comment]
you are missing the peers deps probably in your local install. again it doesn't bundle an entire other version of lodash its going to include like the 10 lines of code that are used in the package.

and in terms of "justified" not everyone is using lodash 4, so there is always someone this would affect.

**Comment by danpantry** [comment]
> you are missing the peers deps probably in your local install

I'm not missing any peer dependencies at all.

The issue is because of `CommonsChunkPlugin`, which isn't respecting the different versions it appears. Throwing one version of lodash in that chunk causes it to completely ignore the other version.

> and in terms of "justified" not everyone is using lodash 4, so there is always someone this would affect.

No, you're right - but the most popular version of Flux currently (Redux) *is* using lodash 4.

The current work around appears to be not to put lodash inside of `CommonsChunkPlugin`. Also, this appears to be more of an issue with CommonsChunkPlugin and not ReactBigCalendar, but I imagine other users may come across this issue in the future.

**Comment by jquense** [comment]
#86

**Comment by frankwallis** [comment]
For anyone else experiencing issues with lodash 3.x methods not being resolved, I found the following webpack configuration will force everything to lodash 4.x:

```
 resolve: {
            alias: {
                'lodash/array/chunk': 'lodash/chunk', /* react-big-calendar still uses lodash 3.x */
                'lodash/object/omit': 'lodash/omit',
                'lodash/object/transform': 'lodash/transform',
                'lodash/object/mapValues': 'lodash/mapValues',
                'lodash/object/defaults': 'lodash/defaults',
                'lodash/utility/range': 'lodash/range',
                'react-prop-types/lib/componentOrElement': 'react-prop-types/lib/mountable'
            }
        },
```
