### ISSUE TITLE
Not able to Run examples on local

### ISSUE THREAD

**Issue by vikalpgupta-birdeye** [intljusticemission/react-big-calendar#462]
Getting below error while running npm run examples, also having issues running npm run build.

/react-big-calendar/webpack/examples.config.js:3
const { rules, loaders, plugins, stats } = require('webpack-atoms')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/abc/WebstormProjects/react-big-calendar/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

**Comment by jquense** [comment]
You need to use a newer version of node I'd  suggest v6+

**Comment by vikalpgupta-birdeye** [comment]
Still not able to run examples on local, getting this error.

/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack-atoms/index.js:29
  const browsers = DEFAULT_BROWSERS = opts
                                    ^

TypeError: Assignment to constant variable.
    at Object.loaders.css (/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack-atoms/index.js:29:37)
    at Object.rules.css.options [as css] (/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack-atoms/index.js:120:18)
    at Object.<anonymous> (/home/abc/WebstormProjects/react-big-calendar/webpack/examples.config.js:32:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/abc/WebstormProjects/react-big-calendar/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
    at module.exports (/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack/bin/convert-argv.js:107:15)
    at Object.<anonymous> (/home/abc/WebstormProjects/react-big-calendar/node_modules/webpack-dev-server/bin/webpack-dev-server.js:208:50)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-big-calendar@0.14.4 examples: `npm run clean:examples && webpack-dev-server --inline --hot --config webpack/examples.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-big-calendar@0.14.4 examples script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/abc/.npm/_logs/2017-08-03T11_11_48_642Z-debug.log

**npm --v
5.3.0
node --version
v8.0.0**
